# версия синтаксиса
version: '3'

services:
  nginx-lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nginx1
      - nginx2
    networks:
      - app-network

  nginx1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./code:/data/mysite.local
    depends_on:
      - fpm1
      - fpm2
    networks:
      - app-network

  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./code:/data/mysite.local
    depends_on:
      - fpm1
      - fpm2
    networks:
      - app-network

  fpm1:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php # имя будущего образа
    depends_on:
      - redis1
      - redis2
      - redis3
    environment:
      - FPM_ID=1
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  fpm2:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php # имя будущего образа
    depends_on:
      - redis1
      - redis2
      - redis3
    environment:
      - FPM_ID=2
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  redis1:
    image: redis:7-alpine
    volumes:
      - redis1_data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
    networks:
      - app-network
    command: redis-server /usr/local/redis/redis.conf

  redis2:
    image: redis:7-alpine
    volumes:
      - redis2_data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
    networks:
      - app-network
    command: redis-server /usr/local/redis/redis.conf

  redis3:
    image: redis:7-alpine
    volumes:
      - redis3_data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
    networks:
      - app-network
    command: redis-server /usr/local/redis/redis.conf

  redis4:
    image: redis:7-alpine
    volumes:
      - redis4_data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
    networks:
      - app-network
    command: redis-server /usr/local/redis/redis.conf

  redis5:
    image: redis:7-alpine
    volumes:
      - redis5_data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
    networks:
      - app-network
    command: redis-server /usr/local/redis/redis.conf

  redis6:
    image: redis:7-alpine
    volumes:
      - redis6_data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
    networks:
      - app-network
    command: redis-server /usr/local/redis/redis.conf

networks:
  app-network:
    driver: bridge

volumes:
  redis1_data:
  redis2_data:
  redis3_data:
  redis4_data:
  redis5_data:
  redis6_data: