# версия синтаксиса
version: '3'

services:
  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nginx1
      - nginx2
    networks:
      - app-network

  nginx1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx1
    volumes:
      - ./code:/data/mysite.local
    depends_on:
      - fpm1
      - fpm2
    networks:
      - app-network

  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx2
    volumes:
      - ./code:/data/mysite.local
    depends_on:
      - fpm1
      - fpm2
    networks:
      - app-network

  fpm1:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php # имя будущего образа
    container_name: fpm1 # имя контейнера после запуска
    depends_on:
      - redis
    environment:
      - FPM_ID=1
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  fpm2:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php # имя будущего образа
    container_name: fpm2 # имя контейнера после запуска
    depends_on:
      - redis
    environment:
      - FPM_ID=2
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: